dbt_ecommerce:
  outputs:
    dev:
      dataset: "{{ env_var('GOOGLE_CLOUD_DATASET') }}"
      job_execution_timeout_seconds: 500
      job_retries: 1
      keyfile: /Users/welitonborges/Documents/_git/dbt_ecommerce/bigquery_keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      threads: 4
      type: bigquery
  target: dev